a=int(input("Enter the first number: "))
b=int(input("Enter the second number:"))
c=int (input("enter the third number:"))
sum= (a+b+c)
avarage=(sum/3)
print("the sum of 3 numbers is ",sum)
print("the avarage of  3 numbers is :",avarage)